### ISSUE TITLE
Regression in support for linear arrays in local memory in v0.8.1

### ISSUE THREAD

**Issue by MoFtZ** [m4rs-mt/ILGPU#191] opened 2020-07-13 11:34 UTC
In ILGPU v0.8.1, the following kernel fails to compile on Cuda accelerators with an internal compiler error - see attached [stackTrace.txt](https://github.com/m4rs-mt/ILGPU/files/4912118/stackTrace.txt).

```
private static void BadKernel(Index1 index, ArrayView<int> data)
{
    if (index >= 0)
    {
        var records = new int[2];
        records[0] = default;
    }
}
```

In ILGPU v0.8.0, the kernel compiled on Cuda accelerators without issue.
Also note that in ILGPU v0.8.1, removing the `if` will remove the compiler error.

**Comment by m4rs-mt** [comment] 2020-07-14 12:50
@MoFtZ I can confirm that this piece of code cannot be compiled with the latest ILGPU version.

**Comment by m4rs-mt** [comment] 2020-07-14 12:51
A quick analysis showed that the problem was introduced in d124ef14bcd39b30a77ff933967a9aae28bd040b. The previous code was also incorrect, but worked by accident 😄 . However, the patch simply assumes that the allocation position can be merged into the entry block, which is actually wrong. Instead, it must be checked whether the value is allocated within the scope of the entry block. If yes, set up the insertion position; if no, find a suitable place there to perform the allocation. I will prepare a patch 🤓

**Closed** 2020-07-23 11:29 UTC
Labels: bug
