### ISSUE TITLE
ILGPU 0.5 : misaligned address with byte arrays

### ISSUE THREAD

**Issue by samy2** [m4rs-mt/ILGPU#12] opened 2019-02-07 21:14 UTC
Hi,
I just tested IlGPU 0.5.
Some of my kernels cannot be executed with the CUDA backend, because of "misaligned address" CudaException when i'm using byte arrays.
Here is a minified sample :

	[Test]
	public void Kernel6Test()
	{
		using (var context = new Context())
		{
			using (var gpu = new CudaAccelerator(context))
			{
				var kernel = gpu.LoadKernel<GroupedIndex, ArrayView<byte>>(Kernel6);
				var gpu_array = gpu.Allocate<byte>(2);
				kernel(gpu.DefaultStream, new GroupedIndex(1, 1), gpu_array);
				var result = gpu_array.GetAsArray(gpu.DefaultStream);
				Assert.AreEqual(1, result[1]);
			}
		}
	}

	private static void Kernel6(GroupedIndex index, ArrayView<byte> gpu_array)
	{
		gpu_array[1] = 1;
	}

**Comment by m4rs-mt** [comment] 2019-02-09 10:01
@samy2 Thanks for your bug report; I couldn't believe that such a simple code wouldn't work. I have extended the internal tests and can reproduce your problem.

It turns out that reading and writing 8-bit types is broken in some cases due to invalid load/store instructions in the PTX backend.

The following PTX code snippet shows this problem:
```
add.u64	%rd2, %rd1, %rd3;
mov.b16	%rs1, 1;
st.b16	[%rd2], %rs1;
```
However, the store instruction should be `st.b8`. Surprisingly this problem does not occur in very sophisticated scenarios. I will fix these issues.

Suggested workaround: use `short` or `int` types at the moment.

**Comment by samy2** [comment] 2019-02-09 18:28
@m4rs-mt
Yes using short instead of byte worked as a workaround. After that, my kernels are working great !
The compilation time is better compared to ilgpu 0.3.0, by a significant margin. Excellent work !
The execution time of my kernels are almost as fast compared to to ilgpu 0.3.0 (overall, the execution time of my application, consisting of the execution of lots of small kernels is one stream is about 2% slower, which is not a big deal).

**Comment by m4rs-mt** [comment] 2019-02-21 19:49
@samy2 Thanks a lot for your feedback! I am definitely going to improve runtime performance of the kernels in future releases.

**Comment by m4rs-mt** [comment] 2019-03-04 18:14
The last commits should fix the reported problem. I will close this issue for now.

**Closed by m4rs-mt** 2019-03-04 18:14 UTC
Labels: bug
