### ISSUE TITLE
Debug symbols for Roslyn-generated in-memory assembly

### ISSUE THREAD

**Issue by ogoshen** [m4rs-mt/ILGPU#10] opened 2018-12-25 11:31 UTC
Using 0.3.0, when running in debug mode, with an in-memory assembly generated with Roslyn I get this:

`System.ArgumentException: The path is not of a legal form.
Parameter name: path
   at System.IO.Path.GetDirectoryName(String path)
   at ILGPU.Compiler.DebugInformation.DebugInformationManager.TryLoadSymbols(Assembly assembly, AssemblyDebugInformation& assemblyDebugInformation)
   at ILGPU.Compiler.DebugInformation.DebugInformationManager.TryLoadDebugInformation(MethodBase methodBase, MethodDebugInformation& methodDebugInformation)
   at ILGPU.Compiler.DebugInformation.DebugInformationManager.LoadSequencePoints(MethodBase methodBase)
   at ILGPU.CompilationContext.EnterMethod(MethodBase method)
   at ILGPU.CompileUnit.GetMethod(MethodBase methodBase, Boolean create)
   at ILGPU.CompileUnit.GetMethod(MethodBase methodBase)
   at ILGPU.Backends.PTXBackend.CreateEntry(CompileUnit unit, EntryPoint entryPoint, String& entryPointName)
   at ILGPU.Backends.LLVMBackend.Compile(CompileUnit unit, MethodInfo entry, KernelSpecialization specialization)
   at ILGPU.Backends.Backend.Compile(CompileUnit unit, MethodInfo entry)`

Everything's peachy in release builds.

Maybe I'm missing something, but there doesn't seem to be a way to supply custom PDBs not from files. I'd expect to have an option to build an `AssemblyDebugInformation`  or give `DebugInformationManager` a stream.

Also a related question, can I somehow compile a kernel without loading the assembly? maybe some kind of Mono.Cecil integration? I'm using core 2.0 and there doesn't seem to be a way to unload assemblies (no AppDomain, Assembly.ReflectionOnlyLoad, or collectible AssemblyLoadContext)

**Comment by m4rs-mt** [comment] 2018-12-30 00:33
I am able to reproduce your problem with an in-memory assembly. Please provide a minimal working example in the future to speed up the bug tracking process.

It turns out that the `DebugInformationManager` tries to resolve the current assembly path and cannot check whether the file exists or not. I will fix this problem in the next release. Workaround: This problem should not occur in the current beta version (v0.5-beta) unless you use `EnableDebugInformation`.

To your question about debugging custom PDB files: This is currently not possible, since the intended use case of the `DebugInformationManager` is to automatically resolve debug symbols for offline compiled assemblies. However, adding additional methods to load certain PDB files from streams makes sense for more advanced use cases such as yours.

ILGPU is designed to rely on default .Net mechanisms to integrate seamlessly into the .Net ecosystem.
There is (currently) no alternative to passing `Delegate` or `MethodInfo` objects to the kernel loaders, as ILGPU assumes valid .Net `Type` and `MethodBase` information. However, you can create custom methods by using the internal ILGPU IR and manually compiling them into kernel methods.

**Comment by ogoshen** [comment] 2019-01-15 08:34
Thanks for verifying, I've added "better bug reports" to my new year resolutions 🥂 
I wouldn't even know where to begin with IR, sound very low-level and undocumented. 

But actually using Roslyn is a great fit for me, IMHO is probably much easier and more robust than building and emitting dynamic IL for a `Delegate` or `MethodInfo` (once supported).

I've ran into another issue related to this use-case involving what I think is caching. 
I'll describe it here, and if you prefer create another issue (doing my best to reproduce).

Basically, it's a loop of loading some source code, replacing and adding methods with Roslyn, compiling and launching. Each iteration launches the (new) kernel multiple times, the first result each iteration is unchanged (cached?), the next are fine.

My buffers are cleared before launch, and I've tried mangling method names.
I've seen there are classes for `MemoryBufferCache` and `KernelCache` but seems like there's no way of turning the cache off.
My workaround is to dispose and construct new a `Backend`, `Accelerator` and `Context` between runs, which seems wasteful and takes a while.

**Comment by m4rs-mt** [comment] 2019-02-09 13:23
@ogoshen I fully agree that relying on the Roslyn infrastructure is much easier and more robust. I understand your point of view on caching strategies. There are several internal and external caches in the ILGPU infrastructure. The `KernelCache` is based on `WeakReference`s and its own GC thread to avoid memory leaks. As soon as a kernel is disposed of by the .Net GC, the ILGPU GC thread can release the associated datastructures. Although each `Accelerator` instance is assigned a `MemoryBufferCache` instance, ILGPU does not use this cache anywhere. It was added to help users write custom `Accelerator` extensions that require temporary memory. If you do not use the corresponding `MemoryBufferCache`s, you should not get into trouble.

As you mentioned earlier, the disposal of `Backend`, `Accelerator` and `Context` instances is wasteful and time-consuming. Internally, ILGPU uses the classes `IRContext`, `IRTypeContext`, `DebugInformationManager`, `ABI`, and `ArgumentMapper`, which cache information to speed up the compilation process. The internally cached objects must be deleted to reclaim the allocated memory. I've been thinking a lot about additional flags to disable caching. However, I think a number of methods for explicitly deleting internal and external caches on demand is the better way, since you might want to compile multiple kernels in a row (with all caches turned on) and then clear all caches.

**Comment by m4rs-mt** [comment] 2019-03-04 18:29
I have added support for disabling kernel caches and clearing all internal caches. For more information on kernel caching, see `ContextFlags.DisableKernelCaching`. Use `Context.ClearCache(ClearCacheMode.Everything)` to clear all internal caches to recover allocated memory. Please note that clearing the cache is not thread-safe (the documentation will be extended in the next days). I'm closing this issue for now; if you have any problems with caching, we can easily reopen this issue in the future.

**Closed by m4rs-mt** 2019-03-04 18:29 UTC
Labels: feature, question
