### ISSUE TITLE
Multidimensional Buffers/Views (from CpuAccelerator) don't throw an exception (or even hit a breakpoint) on out-of-bounds multidimensional indices

### ISSUE THREAD

**Issue by Nnelg** [m4rs-mt/ILGPU#448] opened 2021-03-23 17:17 UTC
## ToReproduce:

1. Acquire a CpuAccelerator
2. Create a multidimensional view with a certain extent, such as (5, 6, 7)
2. Launch a kernel (practically any kernel) with a (partially?) out-of-bounds extent, such as (8, 7, 6)
3. Run in Debug configuration (Any CPU)
4. Observe that the program behaves as if nothing was wrong
5. Repeat the experiment with a CudaAccelerator
6. Note that a CudaException is thrown

## Notes:

Sometimes a breakpoint is hit in external code, which appears to be what happens when you go outside the bounds of a 1-dimensional CPU buffer.

I suspect what is happening is that the CPU's backend is converting the multidimensional index to a linear index *before* checking if it's in-bounds or not, while an actual GPU either natively supports multidimensional indices or checks the bounds before converting to a linear index.

This issue caused me a lot of trouble when code that failed on a GPU appeared to run fine on a CPU.

## Suggested Fix:

- Have Array Views (of all dimensions) check for being within their extent while in Debug mode.
  - Perhaps even do this for Array Views from Cuda or OpenCL, as this would provide additional feedback.
- Replace the breakpoint that is hit when going outside the bounds of a 1-D view/buffer with a thrown exception, or at least print a warning to the console.

**Comment by m4rs-mt** [comment] 2021-03-23 18:01
@Nnelg Thank you for your very detailed issue report. I will take a closer look at it. This problem is also related to the current redesign of the Memory API (see #421).

> I suspect what is happening is that the CPU's backend is converting the multidimensional index to a linear index before checking if it's in-bounds or not, while an actual GPU either natively supports multidimensional indices or checks the bounds before converting to a linear index.

The code paths are different and the implementation of the assertion checks is also different (see #433). I also agree that the problem may be related to the fact that we do not check all dimensions on the CPU separately.

@MoFtZ I'm not sure if we should create a separate patch at the moment that changes the assertion semantics. Maybe we can investigate what the actual problem is and then integrate that feedback into the current redesign work of the memory API.  What are your thoughts on this?

**Comment by MoFtZ** [comment] 2021-03-23 19:37
@m4rs-mt An initial investigation sounds good. The new memory API should definitely take precedence - we can hold off on related patches until it is ready.

**Comment by m4rs-mt** [comment] 2021-03-30 23:25
@Nnelg I have experimented with different kernels in the context of the CPU accelerator and I can confirm that the problem is related to the fact that the individual dimensions are not properly bounds checked. This problem is fixed in #421, which checks all dimensions of a multidimensional index before checking the computed linear element index.

**Closed** 2021-05-01 14:43 UTC
Labels: bug, help wanted
