### ISSUE TITLE
AccessViolationException thrown for device without proper drivers

### ISSUE THREAD

**Issue by eklann** [m4rs-mt/ILGPU#728] opened 2022-01-21 12:38 UTC
I'm using ILGPU for a semi-generic class, for which I have some unit tests that verifies that stuff works. The problem I have started with the CI system having those tests fail. The root cause of this seems to be that the build agent has no driver installed that supports OpenCL for the device I'm trying to use. And this happens as an AccessViolationException.

In this specific case I can solve the problem by testing with a CPU-type device, or installing proper drivers on the build agents. My main concern is that I don't want something similar to happen at the end user side of things, because the application would die. It would seem logical to me that a device without the proper drivers would either not show up when I list devices from the context, or that it would be possible from some property to see that it is not available for use. At the very least it would be nice with some other type of error, eg. DeviceNotSupportException or whatnot, that I can actually handle, instead of just having the application shut down.

Maybe I am just missing something, or doing something wrong? I'll attach the stack trace I am getting from my test, and a snippet of how I select the device and declare my kernel in the first place.

Stack trace:
```
error	21-Jan-2022 09:50:06	The active test run was aborted. Reason: Test host process crashed : Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
error	21-Jan-2022 09:50:06	Repeat 2 times:
error	21-Jan-2022 09:50:06	--------------------------------
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.OpenCL.CLAPI_0.clBuildProgram_Import(IntPtr, Int32, IntPtr*, System.String, IntPtr, IntPtr)
error	21-Jan-2022 09:50:06	--------------------------------
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.OpenCL.CLAPI_0.clBuildProgram(IntPtr, Int32, IntPtr*, System.String, IntPtr, IntPtr)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.OpenCL.CLAPI.BuildProgram(IntPtr, IntPtr, System.String)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.OpenCL.CLKernel.LoadKernel(ILGPU.Runtime.OpenCL.CLAccelerator, System.String, System.String, ILGPU.Backends.OpenCL.CLCVersion, IntPtr ByRef, IntPtr ByRef, System.String ByRef)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.OpenCL.CLKernel..ctor(ILGPU.Runtime.OpenCL.CLAccelerator, ILGPU.Backends.OpenCL.CLCompiledKernel, System.Reflection.MethodInfo)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.OpenCL.CLAccelerator.CreateKernel(ILGPU.Backends.OpenCL.CLCompiledKernel)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.KernelAccelerator`2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].LoadAutoGroupedKernelInternal(ILGPU.Backends.CompiledKernel, ILGPU.Runtime.KernelInfo ByRef)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel(ILGPU.Backends.CompiledKernel, ILGPU.Runtime.KernelInfo ByRef)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.Accelerator+AutoKernelLoader.LoadKernel(ILGPU.Runtime.Accelerator, ILGPU.Backends.CompiledKernel, ILGPU.Runtime.KernelInfo ByRef)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.Accelerator.LoadGenericKernelDirect[[ILGPU.Runtime.Accelerator+AutoKernelLoader, ILGPU, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](ILGPU.Backends.EntryPoints.EntryPointDescription ByRef, ILGPU.Runtime.KernelSpecialization ByRef, AutoKernelLoader ByRef, ILGPU.Runtime.KernelInfo ByRef)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.Accelerator+<>c__DisplayClass157_0`1[[ILGPU.Runtime.Accelerator+AutoKernelLoader, ILGPU, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<LoadGenericKernel>b__0(AutoKernelLoader ByRef, ILGPU.Runtime.KernelInfo ByRef)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.Accelerator.LoadCachedKernel[[ILGPU.Runtime.Accelerator+AutoKernelLoader, ILGPU, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](ILGPU.Backends.EntryPoints.EntryPointDescription ByRef, ILGPU.Runtime.KernelSpecialization ByRef, AutoKernelLoader ByRef, CachedKernelLoader`2<System.__Canon,AutoKernelLoader>, ILGPU.Runtime.KernelInfo ByRef)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.Accelerator.LoadGenericKernel[[ILGPU.Runtime.Accelerator+AutoKernelLoader, ILGPU, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](ILGPU.Backends.EntryPoints.EntryPointDescription, ILGPU.Runtime.KernelSpecialization, AutoKernelLoader ByRef, ILGPU.Runtime.KernelInfo ByRef)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.Accelerator.LoadGenericKernel[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[ILGPU.Runtime.Accelerator+AutoKernelLoader, ILGPU, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](ILGPU.Backends.EntryPoints.EntryPointDescription ByRef, ILGPU.Runtime.KernelSpecialization ByRef, AutoKernelLoader ByRef, ILGPU.Runtime.KernelInfo ByRef)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Reflection.MethodInfo, ILGPU.Runtime.KernelInfo ByRef)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Reflection.MethodInfo)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedKernel[[ILGPU.Index1D, ILGPU, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[ILGPU.ArrayView`1[[System.Single, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ILGPU, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[ILGPU.ArrayView`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ILGPU, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[ILGPU.ArrayView`1[[System.Single, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ILGPU, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[ILGPU.ArrayView`1[[System.Single, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ILGPU, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](ILGPU.Runtime.Accelerator, System.Action`5<ILGPU.Index1D,ILGPU.ArrayView`1<Single>,ILGPU.ArrayView`1<Int32>,ILGPU.ArrayView`1<Single>,ILGPU.ArrayView`1<Single>>)
error	21-Jan-2022 09:50:06	   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedStreamKernel[[ILGPU.Index1D, ILGPU, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[ILGPU.ArrayView`1[[System.Single, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ILGPU, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[ILGPU.ArrayView`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ILGPU, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[ILGPU.ArrayView`1[[System.Single, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ILGPU, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[ILGPU.ArrayView`1[[System.Single, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ILGPU, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](ILGPU.Runtime.Accelerator, System.Action`5<ILGPU.Index1D,ILGPU.ArrayView`1<Single>,ILGPU.ArrayView`1<Int32>,ILGPU.ArrayView`1<Single>,ILGPU.ArrayView`1<Single>>)
[...A few rows of stack trace from the application code...]
error	21-Jan-2022 09:50:06	   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Span`1<System.Object> ByRef, System.Signature, Boolean, Boolean)
error	21-Jan-2022 09:50:06	   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
error	21-Jan-2022 09:50:06	   at System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
error	21-Jan-2022 09:50:06	   at NUnit.Framework.Internal.Reflect.InvokeMethod(System.Reflection.MethodInfo, System.Object, System.Object[])
error	21-Jan-2022 09:50:06	   at NUnit.Framework.Internal.MethodWrapper.Invoke(System.Object, System.Object[])
error	21-Jan-2022 09:50:06	   at NUnit.Framework.Internal.Commands.TestMethodCommand.InvokeTestMethod(NUnit.Framework.Internal.TestExecutionContext)
error	21-Jan-2022 09:50:06	   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(NUnit.Framework.Internal.TestExecutionContext)
error	21-Jan-2022 09:50:06	   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(NUnit.Framework.Internal.TestExecutionContext)
error	21-Jan-2022 09:50:06	   at NUnit.Framework.Internal.Execution.SimpleWorkItem+<>c__DisplayClass4_0.<PerformWork>b__0()
error	21-Jan-2022 09:50:06	   at NUnit.Framework.Internal.ContextUtils+<>c__DisplayClass1_0`1[[System.__Canon, System.Private.CoreLib, Ve
```

Device selection:
```
var context = Context.CreateDefault();
var device = contect.Devices.OrderByDescending(d => d.MaxNumThreads).First()
var accelerator = device.CreateAccelerator(context);
Action< ... > kernel = accelerator.LoadAutoGroupedStreamKernel< ... >(CalcKernel);
```

The device on the build agent that does not work:
```
Baffin [Type: OpenCL, WarpSize: 64, MaxNumThreadsPerGroup: 256, MemorySize: 2147483648]
``` 

Also: Thanks for a super-nice library that makes it much easier to do stuff on the GPU!

**Comment by MoFtZ** [comment] 2022-01-22 05:03
hi @eklann, welcome to the community.

Why do you say that the build agent has no OpenCL drivers? If you did install drivers, would the failure go away?

As you have noticed, ILGPU has detected an AMD Baffin GPU. Looking at your stack trace, it looks like ILGPU is failing while trying to compile the .NET code for OpenCL. This suggests that ILGPU has detected the OpenCL device, and it has passed some initial tests for compatibility.

The `Device` instance has a `PrintInformation` method that displays some device information. Would it be possible for you to call this method and post the information here?

**Comment by eklann** [comment] 2022-01-22 07:31
I have not been able to install any drivers on that machine, it's mostly just bare windows and the build agent client. So I can't say for sure thats what causing the failure.

I have been able to run the same tests on other machines with both OpenCL and CUDA devices.

The PrintInformation from the device:
```
Device: 
Baffin
  Accelerator Type:                        
OpenCL
  Platform name:                           
AMD Accelerated Parallel Processing
  Platform version:                        
2.1
  Vendor name:                             
Advanced Micro Devices, Inc.
  Vendor:                                  
AMD
  Device type:                             
CL_DEVICE_TYPE_GPU
  Device version:                          
2.0
  Clock rate:                              
1071
 MHz
  OpenCL C version:                        
CL2.0
  OpenCL C -cl-std version:                
CL2.0
  Has FP16 support:                        
True
  Has FP64 support:                        
True
  Has Int64 atomics support:               
True
  Has sub group support:                   
False
  Has generic address space support:       
True
```

**Comment by m4rs-mt** [comment] 2022-01-22 10:44
Hi @eklann, welcome to ILGPU the community 🎉 

The issue you describe sounds like an internal driver issue occurring in the native code of the driver JIT pipeline, as the `AccessViolationException` appears to be thrown within `ILGPU.Runtime.OpenCL.CLAPI_0.clBuildProgram_Import(IntPtr, Int32, IntPtr*, System.String, IntPtr, IntPtr)`. However, as @MoFtZ said, ILGPU was previously able to compile and load small "analysis" kernels when instantiating the `Accelerator`. On the one hand, this may mean that it is a driver-only problem and there is not much we can do about it. On the other hand, the emitted code could be "inappropriate" in a way that it crashes the internal driver, even though it is "valid" OpenCL code. Can you give us more information about the kernel program you are trying to load? Are there any `Atomic` or `FP16` operations being used?

**Comment by eklann** [comment] 2022-01-22 14:23
While I cannot share the exact code of the kernel, I can try to summarize what operations it uses.

The signature includes types: ```Index1D, ArrayView<int>, and ArrayView<float>```

The body of the kernel uses the following:
- Indexing in ArrayViews
- Arithmetic operators ```+  -  *  /  ++  --  %```
- Comparison operators ```<  >```
- Math.Min and Math.Sqrt on floats
- While loops
- Casting of float to int
- Declarations of float and int

I'm not sure what you mean by atomic operations, and the only floatingpoint type used is the regular ```float``` whilch i guess is ```FP32```

**Comment by johnlundberg** [comment] 2022-01-24 09:48
Hi, I work with @eklann and have reproduced the kernel error with a shorter code example that is attached

[ReproduceErrorTest.txt](https://github.com/m4rs-mt/ILGPU/files/7924460/ReproduceErrorTest.txt)

**Comment by m4rs-mt** [comment] 2022-01-24 11:15
@eklann @johnlundberg Thank you for sharing this information and taking the efforts to develop a minimally reproducible example. We will take a closer look. What I can see right away is that you are not using device/hardware-specific intrinsic functions (like the ones I mentioned above and @eklann commented on; for example `Atomic.Add`). Consequently, this significantly reduces the risk of running into OpenCL driver bugs - in theory.

**Comment by johnlundberg** [comment] 2022-01-24 12:37
Not sure I understand, would using Atomic.Add increase or reduce the risk of running into bugs?
I tried changing to Atomic.Add but got the following error:
Error in hsa_code section, at offset 1832:
Instruction has invalid segment (private), expected one of: flat, global, group
LLVM ERROR:
Brig container validation has failed in BRIGAsmPrinter.cpp

**Comment by m4rs-mt** [comment] 2022-01-24 13:20
@johnlundberg Oh, perhaps my comment was misleadingly worded. I meant that *not* using these operations significantly reduces the risk of driver bugs.

**Comment by m4rs-mt** [comment] 2022-01-25 23:13
After analyzing the sample program you provided, it looks like the code emitted by ILGPU can be considered valid OpenCL code. In addition, I was not able to crash the program on our test machines equipped with AMD and Intel GPUs. Based on the call stack and the information given, there is definitely not much we can do about an internal `Segmentation Fault` triggered by the driver. Also, `AccessViolationException`s are not intended to be caught by ILGPU as they represent a corrupted state in the "native" world. 

From a professional point of view, I would personally recommend using the `CudaAccelerator` on client machines. If this is not possible, it might be an option to put the whole GPU part into a separate `AppDomain` environment offered by the .Net runtime.

Note 1: Such an application crash can also occur if your GPU program contains bugs. Since these programs run natively on the underlying hardware, this can even lead to total system failures (e.g. `BlueScreen`s).
Note 2: We are currently working on a Spir-V based Vulkan/OpenCL backend. This should significantly reduce the number of potential issues that can occur with OpenCL.

@MoFtZ do you have any other ideas on how to proceed?

**Comment by MoFtZ** [comment] 2022-01-27 05:30
> @MoFtZ do you have any other ideas on how to proceed?

I'm not sure if there is more to add. I have not been able to reproduce the issue on the device that I have access to.

We could keep trying to reduce the sample program, and that might give some more hints about why it is failing. But if this is a driver issue, it'll be tricky to fix, even if we can reproduce it.

**Comment by johnlundberg** [comment] 2022-02-07 10:39
> @johnlundberg: Can you modify your sample program in way that the number of iterations of the outer loop does not depend on the trip counts of the inner loops? By looking at the code, this might be a pattern that the OpenCL driver is not expecting...

Sorry I missed your edit of the reply so I haven't tried this yet. I will look into it and get back to you.

>  If this is not possible, it might be an option to put the whole GPU part into a separate AppDomain environment offered by the .Net runtime

This is our current plan, to create a CLI tool that test runs the kernel and if it crashes, the application will fall back to run without acceleration. I was however a bit concerned about your mention of BSOD, since the CLI tool would trigger that as well.
If there is no bug in our code, would that still be something we should be concerned about?

**Comment by johnlundberg** [comment] 2022-02-07 10:40
I can also mention that I updated the drivers to the latest version and that did not resolve the issue.

**Comment by m4rs-mt** [comment] 2022-06-09 21:10
We are closing this issue for now. If the general problem persists, we can safely reopen this issue.

**Closed by m4rs-mt** 2022-06-09 21:10 UTC
Labels: help wanted, question
