### ISSUE TITLE
OpenCL (AMD) not working on Linux (manjaro)

### ISSUE THREAD

**Issue by jiatao99** [m4rs-mt/ILGPU#333] opened 2020-12-01 02:10 UTC
The following line alway return null. Why?

```
  var openClId = Accelerator.Accelerators.FirstOrDefault(a => a.AcceleratorType.Equals(AcceleratorType.OpenCL));
```

1. System: Linux (manjaro)
2. GPU: AMD RX580
3. CPU: Ryzen 3900x
4. Installed `opencl-amd` 
5. Installed `clinfo` which report back correct OpenCL driver (1.2 C)

I also set the `LD_LIBRARY_PATH` environment variable to `/etc/OpenCL/venders` which contains OpenCL loader. I also tried `LD_LIBRARY_PATH` with `/usr/lib` which contains `libOpenCL.so` without success.

However, I still get null reference. Any idea?

**Comment by m4rs-mt** [comment] 2020-12-01 16:07
@jiatao99 Thank you for your issue report and welcome to the ILGPU community. Hmm seems to be an issue in the detection of the OpenCL accelerators. Maybe the problem is related to the fact that it cannot load the native OpenCL library or ILGPU "thinks" that the GPU is not compatible (although it should support OpenCL 2.0 according to AMD). However, if `1.2 C` refers to the OpenCL (C) version that is currently available via the driver, ILGPU is not able to use this accelerator (OpenCL >= 2.0, only)

Did you also query `CLAccelerator.AllCLAccelerators`? This should include your GPU as long as the native driver interface could be loaded successfully.

**Comment by jiatao99** [comment] 2020-12-01 16:18
I don't see anywhere having a driver for OpenCL(C 2.0) for AMD though. Is there any function that must require 2.0?

Also the macOS does NOT support OpenCL 2.0. 

If 2.0 is NOT an absolute requirement, is it possible to remove this dependency?

**Comment by m4rs-mt** [comment] 2020-12-01 16:35
> I don't see anywhere having a driver for OpenCL(C 2.0) for AMD though. 

I'm not sure I understood your point of view in this context. There are definitely people out there who run ILGPU with AMD cards if that was your question.

> Is there any function that must require 2.0?

OpenCL programs operate on pointers living in different address spaces (can be seen as different "regions" in memory). By default, all pointers work on the "generic" address space (any region in memory), which is specialized later in the compilation process to point to a specific memory region. However, there are cases in which is not possible to decide on a particular address space in the first place. In these cases, ILGPU emits operations working on the "generic" address space. This restriction becomes weaker and weaker, because we add more and more new transformations and specialization steps.

> If 2.0 is NOT an absolute requirement, is it possible to remove this dependency?

Unfortunately, due to the nature of the current compilation pipeline as described above, this is not easily possible.

**Comment by jiatao99** [comment] 2020-12-01 16:47
I tried to set LD_LIBRARY_PATH with `/usr/lib` which contains `libOpenCL.so`. However, CLAccelerator.AllCLAccelerators still returns empty collection. In mac, I can get the AMD cpu like I mentioned in another thread.

**Comment by m4rs-mt** [comment] 2020-12-04 22:30
@jiatao99 It looks like we broke the `OpenCL` support on Linux since the library loader should load `OpenCL` (without the `lib` prefix), like in the case of MacOS. As far as I remember, there is no OpenCL driver for AMD Ryzen CPUs available for Windows and Linux. However, you should be able to enumerate the AMD GPU in your system. Can you try out the upcoming beta `v0.10.0-beta`, which will be available in a couple of days?

**Comment by m4rs-mt** [comment] 2020-12-10 21:21
@jiatao99 Did you have chance to test the latest `v0.10.0-beta` on your system?

**Comment by jiatao99** [comment] 2020-12-10 23:57
Thanks for your email. I followed your instructions, however it still
doesn't work.

I think it is defect item. I liked the robot, however this is soo anoying

**Comment by m4rs-mt** [comment] 2021-02-05 02:07
I am closing this issue for now. If the problem persists, we can always reopen it.

**Closed by m4rs-mt** 2021-02-05 02:07 UTC
Labels: question
