### ISSUE TITLE
ILGPU not picking up the amd gpu for the opencl accerlation

### ISSUE THREAD

**Issue by 12345swordy** [m4rs-mt/ILGPU#49] opened 2019-12-04 13:14 UTC
opencl information regarding my gpu:
Num OpenCL platforms: 1
- CL_PLATFORM_NAME: AMD Accelerated Parallel Processing
- CL_PLATFORM_VENDOR: Advanced Micro Devices, Inc.
- CL_PLATFORM_VERSION: OpenCL 2.1 AMD-APP (2841.5)
- CL_PLATFORM_PROFILE: FULL_PROFILE
- Num devices: 1

  - CL_DEVICE_NAME: Ellesmere
  - CL_DEVICE_VENDOR: Advanced Micro Devices, Inc.
  - CL_DRIVER_VERSION: 2841.5
  - CL_DEVICE_PROFILE: FULL_PROFILE
  - CL_DEVICE_VERSION: OpenCL 1.2 AMD-APP (2841.5)
  - CL_DEVICE_TYPE: GPU
  - CL_DEVICE_VENDOR_ID: 0x1002
  - CL_DEVICE_MAX_COMPUTE_UNITS: 36
  - CL_DEVICE_MAX_CLOCK_FREQUENCY: 1360MHz
  - CL_DEVICE_ADDRESS_BITS: 32
  - CL_DEVICE_MAX_MEM_ALLOC_SIZE: 3145728KB
  - CL_DEVICE_GLOBAL_MEM_SIZE: 3072MB
  - CL_DEVICE_MAX_PARAMETER_SIZE: 1024
  - CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE: 64 Bytes
  - CL_DEVICE_GLOBAL_MEM_CACHE_SIZE: 16KB
  - CL_DEVICE_ERROR_CORRECTION_SUPPORT: NO
  - CL_DEVICE_LOCAL_MEM_TYPE: Local (scratchpad)
  - CL_DEVICE_LOCAL_MEM_SIZE: 32KB
  - CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE: 3145728KB
  - CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS: 3
  - CL_DEVICE_MAX_WORK_ITEM_SIZES: [1024 ; 1024 ; 1024]
  - CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
  - CL_EXEC_NATIVE_KERNEL: 10707028
  - CL_DEVICE_IMAGE_SUPPORT: YES
  - CL_DEVICE_MAX_READ_IMAGE_ARGS: 128
  - CL_DEVICE_MAX_WRITE_IMAGE_ARGS: 8
  - CL_DEVICE_IMAGE2D_MAX_WIDTH: 16384
  - CL_DEVICE_IMAGE2D_MAX_HEIGHT: 16384
  - CL_DEVICE_IMAGE3D_MAX_WIDTH: 2048
  - CL_DEVICE_IMAGE3D_MAX_HEIGHT: 2048
  - CL_DEVICE_IMAGE3D_MAX_DEPTH: 2048
  - CL_DEVICE_MAX_SAMPLERS: 16
  - CL_DEVICE_PREFERRED_VECTOR_WIDTH_CHAR: 4
  - CL_DEVICE_PREFERRED_VECTOR_WIDTH_SHORT: 2
  - CL_DEVICE_PREFERRED_VECTOR_WIDTH_INT: 1
  - CL_DEVICE_PREFERRED_VECTOR_WIDTH_LONG: 1
  - CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT: 1
  - CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE: 1
  - CL_DEVICE_EXTENSIONS: 25
  - Extensions:
    - cl_khr_fp64
    - cl_amd_fp64
    - cl_khr_global_int32_base_atomics
    - cl_khr_global_int32_extended_atomics
    - cl_khr_local_int32_base_atomics
    - cl_khr_local_int32_extended_atomics
    - cl_khr_int64_base_atomics
    - cl_khr_int64_extended_atomics
    - cl_khr_3d_image_writes
    - cl_khr_byte_addressable_store
    - cl_khr_fp16
    - cl_khr_gl_sharing
    - cl_amd_device_attribute_query
    - cl_amd_vec3
    - cl_amd_printf
    - cl_amd_media_ops
    - cl_amd_media_ops2
    - cl_amd_popcnt
    - cl_khr_d3d10_sharing
    - cl_khr_d3d11_sharing
    - cl_khr_dx9_media_sharing
    - cl_khr_image2d_from_buffer
    - cl_khr_spir
    - cl_khr_gl_event
    - cl_amd_liquid_flash

**Comment by m4rs-mt** [comment] 2019-12-05 12:01
@12345swordy So I assume the desired AMD GPU does not occur in the list of `Accelerator.Accelerators`? If no, can you try to enumerate all OpenCL devices in your system using `CLAccelerator.AllCLAccelerators` (more information [here](http://www.ilgpu.net/Documentation/UpgradeGuide)) and check whether your GPU does occur in this list?

**Comment by 12345swordy** [comment] 2019-12-05 14:14
> 
> 
> @12345swordy So I assume the desired AMD GPU does not occur in the list of `Accelerator.Accelerators`? If no, can you try to enumerate all OpenCL devices in your system using `CLAccelerator.AllCLAccelerators` (more information [here](http://www.ilgpu.net/Documentation/UpgradeGuide)) and check whether your GPU does occur in this list?

'CLAccelerator.AllCLAccelerators.Length' returns zero. I did however try to debug this, by attempting to duplicate the  CLAccelerator() function seen [here](https://github.com/m4rs-mt/ILGPU/blob/4c553aa99c564a9f4f632d7d32c56dd8b0430e54/Src/ILGPU/Runtime/OpenCL/CLAccelerator.cs#L108)
It fails at the CLAPI.GetNumDevices() function, which returns the "CL_INVALID_VALUE", error.

**Comment by m4rs-mt** [comment] 2019-12-06 00:32
@12345swordy All right - it looks like the OpenCL API function `clGetDeviceIDs` is not used properly on your platform. According to the [documentation](https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clGetDeviceIDs.html) `CL_INVALID_VALUE` should be returned "if num_entries is equal to zero and device_type is not NULL or if both num_devices and device_type are NULL" (OpenCL documentation). However, in order to detect the number of available devices in the system I simply use the following code snippet (CLAPI.cs):
```
NativeMethods.GetDeviceIDs(platform, deviceType, short.MaxValue, null, out numDevices);
```
Maybe the maximum number of devices `short.MaxValue` is simply to large for the AMD OpenCL runtime in your case? Can you clone the repository and change this value to `byte.MaxValue` or just `32`, for instance?

**Comment by 12345swordy** [comment] 2019-12-06 02:08
Changing the maxNumDevices value didn't help. I even set it to one and it still fails. If I skipped the getnumdevices function and assume that the number of devices is one, it surprisingly works well! Going to try to duplicated this on other .net open-cl binding libraries on this.

**Comment by 12345swordy** [comment] 2019-12-06 02:50
Ok I think I have find out what the problem is. You can't pass null to the devices parameter for the GetDeviceIDs function. AMD for some reason doesn't like that. I fix it by changing the GetNumDevices function by the following
```
        public static CLError GetNumDevices(IntPtr platform, CLDeviceType deviceType, out int numDevices) =>
            GetDevices(
                platform,
                deviceType,
                new IntPtr[short.MaxValue],
                out numDevices);
```

**Comment by m4rs-mt** [comment] 2019-12-06 05:29
All right. However, I guess the problem is even worse: once we pass a set of device pointers to the function, we should release them later. So I suggest that I simply remove this functionality completely and redesign the static `CLAccelerator` constructor. This should avoid further problems with AMD incompatibilities related to this function.

**Comment by m4rs-mt** [comment] 2019-12-07 07:08
After diving deeper into the OpenCL specification, it turns out that a call to [clReleaseDevice](https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/clReleaseDevice.html) is not required for device IDs resolved by calls to `clGetDeviceIDs`.

**Comment by m4rs-mt** [comment] 2019-12-07 07:16
Besides, the whole problem is even worse. After additional feedback from the community, it seems that some OpenCL drivers report a larger number of devices than the actual ones. This leads to `IntPtr.Zero` values within the passed device ID array, which in turn causes problems in the scope of the `CLAccelerator` constructor.

**Closed** 2019-12-08 08:26 UTC
Labels: workaround required
