### ISSUE TITLE
CudaAccelerator empty result

### ISSUE THREAD

**Issue by LTOctum** [m4rs-mt/ILGPU#31] opened 2019-08-13 12:07 UTC
Hi @m4rs-mt,

found another issue, the `BicubicFilter` works like a charm with `CPU` accelerator, but with `Cuda` it will return an zeroed `destination` array.

May i found some kind of limitation, but there is no error or anything else to debug further.

Any hint from your side what could be wrong?

Thanks in advance.

```
public static class BicubicFilter
    {
        public static void Kernel(Index2 pixelIndex, int originalWidth, int originalHeight, int bpp, int destinationWidth, int destinationHeight, float scaleFactor, ArrayView<byte> source, ArrayView<byte> destination)
        {
            int destLineStride = destinationWidth * bpp;
            int srcLineStride = originalWidth * bpp;
            int destX = pixelIndex.X;
            int destY = pixelIndex.Y;

            float v = (float)destY / (float)(destinationHeight - 1);
            float u = (float)destX / (float)(destinationWidth - 1);


            float x2 = (u * (float)originalWidth) - 0.5f;
            int xint = (int)x2;
            float xfract = x2 - XMath.Floor(x2);

            float y2 = (v * (float)originalHeight) - 0.5f;
            int yint = (int)y2;
            float yfract = y2 - XMath.Floor(y2);



            for (int i = 0; i < bpp; ++i)
            {
                // 1st row
                var p00 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint - 1, yint - 1, i);
                var p01 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint + 0, yint - 1, i);
                var p02 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint + 1, yint - 1, i);
                var p03 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint + 2, yint - 1, i);

                // 2nd row
                var p10 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint - 1, yint + 0, i);
                var p11 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint + 0, yint + 0, i);
                var p12 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint + 1, yint + 0, i);
                var p13 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint + 2, yint + 0, i);

                // 3rd row
                var p20 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint - 1, yint + 1, i);
                var p21 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint + 0, yint + 1, i);
                var p22 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint + 1, yint + 1, i);
                var p23 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint + 2, yint + 1, i);

                // 4th row
                var p30 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint - 1, yint + 2, i);
                var p31 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint + 0, yint + 2, i);
                var p32 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint + 1, yint + 2, i);
                var p33 = GetPixelClamped(source, originalWidth, originalHeight, bpp, srcLineStride, xint + 2, yint + 2, i);


                float col0 = CubicHermite(p00, p10, p20, p30, xfract);
                float col1 = CubicHermite(p01, p11, p21, p31, xfract);
                float col2 = CubicHermite(p02, p12, p22, p32, xfract);
                float col3 = CubicHermite(p03, p13, p23, p33, xfract);
                float value = CubicHermite(col0, col1, col2, col3, yfract);
                value = XMath.Clamp(value, 0.0f, 255.0f);
                destination[(destY * destLineStride) + (destX * bpp) + i] = (byte)value;
            }
        }

        private static byte GetPixelClamped(ArrayView<byte> src, int originalWidth, int originalHeight, int bpp, int stride, int x, int y, int colorIndex)
        {
            x = XMath.Clamp(x, 0, originalWidth - 1);
            y = XMath.Clamp(y, 0, originalHeight - 1);
            return src[(y * stride) + (x * bpp) + colorIndex];
        }

        private static float CubicHermite(float A, float B, float C, float D, float t)
        {
            float a = -A / 2.0f + (3.0f * B) / 2.0f - (3.0f * C) / 2.0f + D / 2.0f;
            float b = A - (5.0f * B) / 2.0f + 2.0f * C - D / 2.0f;
            float c = -A / 2.0f + C / 2.0f;
            float d = B;

            return a * t * t * t + b * t * t + c * t + d;
        }
    }
```

**Comment by LTOctum** [comment] 2019-08-13 12:33
Changing `GetPixelClamped` from `byte`  to `float` solves the problem.

```
private static float GetPixelClamped(ArrayView<byte> src, int originalWidth, int originalHeight, int bpp, int stride, int x, int y, int colorIndex)
        {
            x = XMath.Clamp(x, 0, originalWidth - 1);
            y = XMath.Clamp(y, 0, originalHeight - 1);
            return (float)src[(y * stride) + (x * bpp) + colorIndex];
        }
```

But this seems more like a workaround.

**Comment by m4rs-mt** [comment] 2019-08-19 17:27
I can reproduce the problem with the source code provided. The problem is an invalid conversion of an unsigned `int8` to a `float` value. Currently the compiler generates a signed conversion from `sbyte` to `float` instead of the intended unsigned conversion. This bug will be fixed in one of the upcoming commits.

At the moment I recommend to first convert the `byte` value to a default value of `int` (32bit integer) before converting it to a `float` value.

**Closed** 2019-08-22 20:46 UTC
Labels: bug
