### ISSUE TITLE
Incompatibility with custom struct

### ISSUE THREAD

**Issue by weierstrass1** [m4rs-mt/ILGPU#64] opened 2020-02-05 03:20 UTC
i was trying to use a custom struct with the library but it says me that it is not supported:

using SMWControlLibRendering.Interfaces;

```
namespace SMWControlLibRendering.Colors
{
    public struct ColorR5G5B5 : ICanBeMultibytes
    {
        /// <summary>
        /// Gets or sets the r.
        /// </summary>
        public byte R { get; set; }
        /// <summary>
        /// Gets or sets the g.
        /// </summary>
        public byte G { get; set; }
        /// <summary>
        /// Gets or sets the b.
        /// </summary>
        public byte B { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ColorR5G5B5"/> class.
        /// </summary>
        /// <param name="r">The r.</param>
        /// <param name="g">The g.</param>
        /// <param name="b">The b.</param>
        public ColorR5G5B5(byte r, byte g, byte b)
        {
            R = r;
            G = g;
            B = b;
        }
        public static implicit operator int(ColorR5G5B5 col)
        {
            return (col.R << 16) | (col.G << 8) | col.B;
        }
        public static implicit operator bool(ColorR5G5B5 col)
        {
            return ((col.R & 0x07) | (col.G & 0x07) | (col.B & 0x07)) != 0;
        }

        /// <summary>
        /// Sets the byte.
        /// </summary>
        /// <param name="index">The index.</param>
        /// <param name="b">The b.</param>
        public void SetByte(int index, byte b)
        {
            switch(index)
            {
                case 0:
                    R = b;
                    break;
                case 1:
                    G = b;
                    break;
                default:
                    B = b;
                    break;
            }
        }
    }
}
```

![image](https://i.gyazo.com/6425251498af50b97423a0c6ca5d58c5.png)

```
using ILGPU;
using System;

namespace SMWControlLibRendering.KernelStrategies.BitmapBuffer
{
    /// <summary>
    /// The draw bitmap buffer with zoom.
    /// </summary>
    public class DrawBitmapBufferWithZoom<T> : KernelStrategy<Index2, ArrayView<T>, ArrayView<T>, int, int, int, int> where T : struct
    {
        private static readonly DrawBitmapBufferWithZoom<T> instance = new DrawBitmapBufferWithZoom<T>();
        /// <summary>
        /// Executes the.
        /// </summary>
        /// <param name="index">The index.</param>
        /// <param name="destBuffer">The dest buffer.</param>
        /// <param name="srcBuffer">The src buffer.</param>
        /// <param name="offset">The offset.</param>
        /// <param name="dstWidth">The dst width.</param>
        /// <param name="srcWidth">The src width.</param>
        /// <param name="zoom">The zoom.</param>
        public static void Execute(Index2 index, ArrayView<T> destBuffer, ArrayView<T> srcBuffer, int offset,
            int dstWidth, int srcWidth, int zoom)
        {
            instance.strategy(index, destBuffer, srcBuffer, offset, dstWidth, srcWidth, zoom);
            HardwareAcceleratorManager.GPUAccelerator.Synchronize();
        }
        /// <summary>
        /// strategies the.
        /// </summary>
        /// <param name="index">The index.</param>
        /// <param name="destBuffer">The dest buffer.</param>
        /// <param name="srcBuffer">The src buffer.</param>
        /// <param name="offset">The offset.</param>
        /// <param name="dstWidth">The dst width.</param>
        /// <param name="srcWidth">The src width.</param>
        /// <param name="zoom">The zoom.</param>
        protected override void strategy(Index2 index, ArrayView<T> destBuffer, ArrayView<T> srcBuffer, int offset,
            int dstWidth, int srcWidth, int zoom)
        {
            T color = srcBuffer[(index.Y * srcWidth) + index.X];

            if (Convert.ToBoolean(color))
                return;

            int jw = offset;
            for (int j = 0; j < zoom; j++)
            {
                jw += dstWidth;
                for (int i = 0; i < zoom; i++)
                {
                    destBuffer[jw + i] = color;
                }
            }
        }
    }
}
    /// <summary>
    /// The kernel strategy.
    /// </summary>
    public abstract class KernelStrategy<T, U, V, W, X, Y, Z> : Strategy<T, U, V, W, X, Y, Z> where T : struct, IIndex
                                                                                        where U : struct
                                                                                        where V : struct
                                                                                        where W : struct
                                                                                        where X : struct
                                                                                        where Y : struct
                                                                                        where Z : struct
    {
        /// <summary>
        /// Gets or sets the kernel.
        /// </summary>
        protected Action<T, U, V, W, X, Y, Z> kernel { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="KernelStrategy"/> class.
        /// </summary>
        public KernelStrategy()
        {
            kernel = HardwareAcceleratorManager.GPUAccelerator.LoadAutoGroupedStreamKernel<T, U, V, W, X, Y, Z>(strategy);
        }
    }
```
What i am doing wrong?

**Comment by m4rs-mt** [comment] 2020-02-05 18:38
According to the error message the problem is not related to your custom structure type. I guess the problem is related to your instance function "strategy" that is invoked on a class type.

**Comment by weierstrass1** [comment] 2020-02-05 20:03
could be the Convert.ToBoolean ??

**Comment by m4rs-mt** [comment] 2020-02-06 23:30
@weierstrass1 I accidentally did not see your `Convert.ToBoolean` call. Yes, this will also cause problems as it should be using the overloaded `Convert.ToBoolean(object?)` version (as far as I can see). This includes boxing, which is not supported in general.

**Comment by weierstrass1** [comment] 2020-02-07 02:43
I did another method trying to don't use Convert. But also send me the same:

System.NotSupportedException: 'Class type 'SMWControlLibRendering.KernelStrategies.IndexedBitmapBufferKernels.CreateBitmapBufferWithZoomByteRGB555Kernel' is not supported'

```
using ILGPU;

namespace SMWControlLibRendering.KernelStrategies.IndexedBitmapBufferKernels
{
    /// <summary>
    /// The create bitmap with zoom.
    /// </summary>
    public class CreateBitmapBufferWithZoomByteRGB555Kernel : KernelStrategy<Index2, ArrayView2D<byte>, ArrayView<byte>, ArrayView<byte>, int, int>
    {
        //private static readonly CreateBitmapBufferWithZoomByteRGB555Kernel instance = new CreateBitmapBufferWithZoomByteRGB555Kernel();
        /// <summary>
        /// Executes the.
        /// </summary>
        /// <param name="index">The index.</param>
        /// <param name="indexedBitmapBuffer">The indexed bitmap buffer.</param>
        /// <param name="destBitmap">The dest bitmap.</param>
        /// <param name="colors">The colors.</param>
        /// <param name="zoom">The zoom.</param>
        /// <param name="flip">The flip.</param>
        public void Execute(Index2 index, ArrayView2D<byte> indexedBitmapBuffer, ArrayView<byte> destBitmap, ArrayView<byte> colors, int zoom, int flip)
        {
            kernel(index, indexedBitmapBuffer, destBitmap, colors, zoom, flip);
            HardwareAcceleratorManager.GPUAccelerator.Synchronize();
        }
        /// <summary>
        /// strategies the.
        /// </summary>
        /// <param name="index">The index.</param>
        /// <param name="indexedBitmapBuffer">The indexed bitmap buffer.</param>
        /// <param name="destBitmap">The dest bitmap.</param>
        /// <param name="colors">The colors.</param>
        /// <param name="zoom">The zoom.</param>
        /// <param name="flip">The flip.</param>
        protected override void strategy(Index2 index, ArrayView2D<byte> indexedBitmapBuffer, ArrayView<byte> destBitmap, ArrayView<byte> colors, int zoom, int flip)
        {
            /*int colind = indexedBitmapBuffer[index] * 3;
            if (colind != 0)
            {
                
                int y = index.Y;
                if ((flip & 0x2) != 0)
                    y = indexedBitmapBuffer.Height - y - 1;
                int x = index.X;
                if ((flip & 0x1) != 0)
                    x = indexedBitmapBuffer.Width - x - 1;
                
                byte colorR = colors[colind];
                byte colorG = colors[colind + 1];
                byte colorB = colors[colind + 2];

                int wz = indexedBitmapBuffer.Width * zoom;
                int offset = ((y * indexedBitmapBuffer.Width) + x) * zoom;
                int wzz = wz * zoom;
                for (int j = 0; j < wzz; j += wz)
                {
                    for (int i = 0; i < zoom; i++)
                    {
                        int ind = (offset + j) * 3;
                        destBitmap[ind] = colorR;
                        destBitmap[ind + 1] = colorG;
                        destBitmap[ind + 2] = colorB;
                    }
                }
            }*/
        }
    }
}
```
```
    /// <summary>
    /// The kernel strategy.
    /// </summary>
    public abstract class KernelStrategy<T, U, V, W, X, Y> : Strategy<T, U, V, W, X, Y> where T : struct, IIndex
                                                                                        where U : struct
                                                                                        where V : struct
                                                                                        where W : struct
                                                                                        where X : struct
                                                                                        where Y : struct
    {
        /// <summary>
        /// Gets or sets the kernel.
        /// </summary>
        protected Action<T, U, V, W, X, Y> kernel { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="KernelStrategy"/> class.
        /// </summary>
        public KernelStrategy()
        {
            kernel = HardwareAcceleratorManager.GPUAccelerator.LoadAutoGroupedStreamKernel<T, U, V, W, X, Y>(strategy);
        }
    }
```
The method do literally nothing but still send me the error, it doesn't use any custom struct.

**Comment by m4rs-mt** [comment] 2020-02-07 08:39
@weierstrass1 As I previously said, 
> According to the error message the problem is not related to your custom structure type. I guess the problem is related to your instance function "strategy" that is invoked on a class type.

If you use an instance method, the `this` pointer is a class type, which in turn is not supported. Use a static kernel method to ensure that you are not accessing any class fields.

**Comment by weierstrass1** [comment] 2020-02-08 01:37
Okz, now it is working, thanks for your help :). I last question, how can i know how much cores have each accelerator? i want to distribute methods between cpu and gpu depends on the number of cores of each.

**Comment by m4rs-mt** [comment] 2020-02-19 20:21
Using the directly accessible accelerator properties you can get detailed information about all available threads/MPs/group configurations etc. Details can be found [here](https://github.com/m4rs-mt/ILGPU.Samples/blob/master/Src/DeviceInfo/Program.cs). However, please keep in mind that a GPU thread or warp cannot simply be transferred to a CPU core in terms of performance or processing capabilities :)

**Closed** 2020-02-24 00:31 UTC
Labels: question
