### ISSUE TITLE
Kernel compiles for CPU but not OpenCL

### ISSUE THREAD

**Issue by Wowo51** [m4rs-mt/ILGPU#181] opened 2020-07-03 06:52 UTC
First, thanks. I got my backtester ported to ILGPU and running in CPU mode with minimal hassle. However when I try to create an OpenCL kernel it fails on this type of line:

independants[startIndependantIndex] = lookBackCandle.Open;

It's the expression on the left of the equals sign that seems to be throwing an error, it doesn't seem to matter what I put on the right. I get an error message suggesting that an index is out of bounds for an array but my code runs in CPU Accelerator mode. I'm not even sure if the error has anything to do with my indexing as it's failing on the LoadAutoGroupedStreamKernel call. Might be a compiler bug of a completely different sort of indexing fail. My independants array is declared locally in the body of the kernel, like this:

float[] independants = new float[totalLookBackCandles * 5];

Here's a stack trace:

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Index must be within the bounds of the List. (Parameter 'index'))
  Source=System.Threading.Tasks.Parallel
  StackTrace:
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at ILGPU.IR.Transformations.UnorderedTransformation.Transform[TPredicate](MethodCollection`1 methods)
   at ILGPU.IR.Transformations.Transformer.Transform[THandler](IRContext context, THandler handler, Verifier verifier)
   at ILGPU.IR.IRContext.Transform[THandler](Transformer& transformer, THandler handler)
   at ILGPU.Backends.Backend.Compile[TBackendHook](Method kernelMethod, EntryPointDescription& entry, KernelSpecialization& specialization, TBackendHook backendHook)
   at ILGPU.Backends.Backend.Compile[TBackendHook](EntryPointDescription& entry, KernelSpecialization& specialization, TBackendHook backendHook)
   at ILGPU.Backends.Backend.Compile(EntryPointDescription& entry, KernelSpecialization& specialization)
   at ILGPU.Runtime.Accelerator.CompileKernel(EntryPointDescription& entry, KernelSpecialization& specialization)
   at ILGPU.Runtime.Accelerator.LoadGenericKernelDirect[TKernelLoader](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.<>c__DisplayClass152_0`1.<LoadGenericKernel>b__0(TKernelLoader& loader, KernelInfo& info)
   at ILGPU.Runtime.Accelerator.LoadCachedKernel[TKernelLoader,T](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, CachedKernelLoader`2 cachedLoader, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadGenericKernel[TKernelLoader](EntryPointDescription entry, KernelSpecialization specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadGenericKernel[TDelegate,TKernelLoader](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel[TDelegate](MethodInfo method, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel[TDelegate](MethodInfo method)
   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedKernel[TIndex,T1,T2,T3](Accelerator accelerator, Action`4 action)
   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedStreamKernel[TIndex,T1,T2,T3](Accelerator accelerator, Action`4 action)
   at HardingBacktesterGPU.BacktestBatcher.Initialize(CandleGPU[] candles, Int32 maxNodeListLength) in C:\Users\warre\Desktop\Code 2019\HardingBacktesterGPU\HardingBacktesterGPU\BacktestBatcher.cs:line 31
   at HardingBacktesterGPU.BacktestBridge.Run() in C:\Users\warre\Desktop\Code 2019\HardingBacktesterGPU\HardingBacktesterGPU\BacktestBridge.cs:line 36
   at HardingBacktesterGPUApp.MainWindow.<btnStart_Click>b__6_0() in C:\Users\warre\Desktop\Code 2019\HardingBacktesterGPU\HardingBacktesterGPUApp\MainWindow.xaml.cs:line 75
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentOutOfRangeException: Index must be within the bounds of the List. (Parameter 'index')

Let me know if you need more info. Thanks.

**Comment by Wowo51** [comment] 2020-07-03 08:34
Hmmm, it looks like there might not be support for fixed arrays within the kernel...

**Comment by Wowo51** [comment] 2020-07-03 10:23
I worked around this by removing all arrays that were being declared within the body of the kernel. Reworked it by making do with ArrayViews passed in as arguments.

I found this bizarre glitch. This compiles from within the kernel (OpenCL):

orderQuantity = -1.0f / price;

this didn't:

orderQuantity = 1.0f / price;

a crass workaround:

orderQuantity = -1.0f / -price;

I'm a bit wary still but on the upside the now running OpenCL kernel is way faster than my original C# code.

Cheers!

**Comment by m4rs-mt** [comment] 2020-07-03 10:40
@Wowo51 Thanks a lot for your bug report. Looks like this problem is related to an internal compiler transformation working on Array instances. Can you provide a minimal example based on your code which reproduces this issue? Which version and optimization level do you use?

**Comment by Wowo51** [comment] 2020-07-03 11:58
I'm using the latest version off Nuget, just downloaded it within the last couple of days. I haven't made to the point where I'm playing with the optimization settings, I'm just getting started with your library, so defaults. I'll try and get to writing a minimal example, I'm crushed for time. I am likely going to stick with your library, I'll try not to drown you in reports and questions.

**Comment by belansoft** [comment] 2020-07-13 16:21
Hi. I'm new to ILGPU, but thanks a lot Marcel for this great project!
I'm observing the same kind of issue when compiling a Cuda kernel.
The log is in attached: [stacktrace.txt](https://github.com/m4rs-mt/ILGPU/files/4913649/stacktrace.txt)

I observe this when trying to compile a simple kernel:

byte[] order = new byte[10];
	for (byte pos = 0; pos < order.Length; pos++)
		order[pos] = pos;

byte[] grid = new byte[10];
grid[0] = 0;

I can successfully operate with the first, "order" array inside kernel. Also I can initialize another array variable, the "grid" one with no problem. But once I'm trying to do something with it, e.g. set it's element value, the kernel becomes not compiling. And this failing at the same LoadAutoGroupedStreamKernel call.
I am using the newest available "0.8.1-beta1" version on my netcoreapp3.0 under Linux MInt 20.
Ready to provide any additional info, if needed.
Thanks, and best regards!

**Comment by MoFtZ** [comment] 2020-07-13 19:52
hi @Wowo51 @belansoft @m4rs-mt 

I just realised that this is probably related to the issue I recently raised #191. If so, downgrading to ILGPU v0.8.0 seems to workaround the problem.

**Comment by belansoft** [comment] 2020-07-14 10:18
Hi @MoFtZ. Thanks, version v0.8.0 works with arrays!

However, on that version I'm encountering a problem when using structures like ArrayView2D, which is already addressed in v0.8.1-beta1.
When trying to use that kind of structures on my Linux system, I get the following:
```
Unhandled exception. System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.ArgumentException: Type 'ILGPU.ArrayView`2[System.Double,ILGPU.Index2]' cannot be marshaled as an unmanaged structure; no meaningful size or offset can be computed.
```
As far as I understand, that is related to issue [#116](https://github.com/m4rs-mt/ILGPU/issues/116)...

**Comment by MoFtZ** [comment] 2020-07-14 12:02
hi @belansoft, the only workaround I can suggest is to use v0.8.1 without allocating new arrays in your kernels.

I had a look at the error, but unfortunately I'm not familiar with that part of the code - maybe if I stare at it long enough, it'll make sense 😅. Otherwise, you might need to wait for @m4rs-mt to have some free time.

**Comment by m4rs-mt** [comment] 2020-07-14 12:53
@belansoft @MoFtZ Thank you for your efforts in the bug hunt 🤓 A quick analysis revealed that the problem has been introduced in d124ef14bcd39b30a77ff933967a9aae28bd040b. I have posted additional notes @ #191.

**Comment by m4rs-mt** [comment] 2020-07-14 12:54
@belansoft Regarding the Linux issues you mentioned: exactly; this problem (#116) has been resolved in v0.8.1.

**Comment by m4rs-mt** [comment] 2020-07-14 13:04
@belansoft A possible workaround would be to first allocate all arrays at the beginning of the function.

**Comment by belansoft** [comment] 2020-07-14 13:48
Thanks a lot! I checked on my side, and can confirm that allocating all arrays at the beginning of kernel function helps as a workaround for v0.8.1-beta1.

**Comment by m4rs-mt** [comment] 2020-07-22 09:24
I close this issue for now, as the underlying problem has been summarized in #191.

**Closed by m4rs-mt** 2020-07-22 09:24 UTC
Labels: question
