### ISSUE TITLE
Illegal memory access during Float3 subtraction

### ISSUE THREAD

**Issue by BenjaminPelletier** [m4rs-mt/ILGPU#76] opened 2020-03-28 00:00 UTC
I'm having a bizarre issue with ILGPU.  From a kernel method, I'm calling a subroutine with this signature:

```csharp
KinematicSolution Track(Float3 sunDirection, Float3 target, float tolerance2, KinematicAngles near)
```

In that method, I compute a local variable:

```csharp
Float3 position = ActuatePoint(Zero.Origin, angles);
```

Later in the routine, I have these three final lines:

```csharp
//return new KinematicSolution(new KinematicAngles(0, 0), true);
Float3 targetDelta = target - position;
return new KinematicSolution(new KinematicAngles(0, 0), true);
```

When I run this kernel as part of a unit test in x64 Release configuration, I get `ILGPU.Runtime.Cuda.CudaException: an illegal memory access was encountered`.  If I uncomment that first commented line, I do *not* get that illegal memory access.  This seems to indicate that the subtraction of two `Float3`s is causing the illegal memory access.  WTF?

Now for the bonus: If I switch to x64 Debug configuration and re-run the test that causes the illegal memory access (with the first `return` commented, exactly as above), then I do *not* get the illegal memory access.  This seems to indicate that the subtraction of two `Float3`s is causing an illegal memory access *only in Release configuration*.

Is there any expected behavior from ILGPU that may be causing this issue?  How can I find out why this unexpected behavior is occurring?

**Comment by BenjaminPelletier** [comment] 2020-03-28 00:23
The above was using ILGPU 0.7.1 nuget package with ILGPU Algorithms 0.7.0 package.  When I upgrade to ILGPU 0.8.0-beta1 and ILGPU Algorithms 0.7.1, I get an error during ILGPU compilation:

```
  Message: 
    Test method FieldOptics_Test.SimpleTraceTests.BasicIntegrationTest threw exception: 
    System.ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
  Stack Trace: 
    Delegate.CreateDelegateNoSecurityCheck(Type type, Object target, RuntimeMethodHandle method)
    DynamicMethod.CreateDelegate(Type delegateType, Object target)
    Kernel.CreateLauncherDelegate[TDelegate]()
    Accelerator.LoadGenericKernel[TDelegate,TKernelLoader](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader)
    Accelerator.LoadAutoGroupedKernel[TDelegate](MethodInfo method)
    KernelLoaders.LoadAutoGroupedKernel[TIndex,T1,T2,T3,T4,T5](Accelerator accelerator, Action`6 action)
    KernelLoaders.LoadAutoGroupedStreamKernel[TIndex,T1,T2,T3,T4,T5](Accelerator accelerator, Action`6 action)
    FieldRaytracer.ctor(Boolean useGpu) line 125
```

I see that Index is now obsolete, so I replaced my kernel Index with Index1 which resolved that issue.  However, the original issue is still present with the exact same behavior as described above.

**Comment by BenjaminPelletier** [comment] 2020-03-28 00:39
Experimenting a little more, when I comment out some dead code below the `return` statement, it moves the issue to a different line.  Perhaps I have run out of GPU registers or my kernel is too big to fit on the GPU?  I have a GeForce RTX 2060 so it's not tiny, but on the other hand, my kernel is most certainly non-trivial.  That somewhat makes sense to me, but I would expect to run out of GPU resources when in Debug mode (where additional features are enabled) rather than Release mode (where those debug features are removed), and instead I'm seeing the opposite: issues in Release, but no issues in Debug.

**Comment by m4rs-mt** [comment] 2020-03-30 18:41
@BenjaminPelletier This sounds interesting. ILGPU uses different transformation passes in release mode. Moreover, the C# compiler (usually - depending on your compiler configuration) generates different instructions. This might cause the problem. Can you come up with a simplified example such that I can reproduce this issue?

**Comment by m4rs-mt** [comment] 2020-03-30 18:55
One more thing to take into account: PTX driver bugs. Can you enable `AggressiveInlining` via the `Context` constructor and tell me whether the code still crashes?

**Comment by davidagross** [comment] 2020-03-30 20:14
@m4rs-mt, I have access to this source and will try your suggestion of enabling `AggressiveInlining` before looking into a MWE.  Thanks for getting to this.

**Comment by davidagross** [comment] 2020-03-30 22:42
So `AggressiveInlining` (ORed with `FastMath` which is already in our `Context`) appears to solve the problem of our failing tests in `Release` mode.  Thank you for the suggestion!

So what is the path to closing the issue, here?  Is there still a need for a MWE that demonstrates the effect?  Or now that you know that `AggressiveInlining` fixes this exception, is there a path for you to add this suggestion to the source when the exception is thrown?

**Comment by MoFtZ** [comment] 2020-04-06 01:33
hi @BenjaminPelletier, @davidagross, are  you able to provide a minimum working example? I'd be happy to help investigate the issue.

**Comment by m4rs-mt** [comment] 2020-04-06 08:16
@MoFtZ @davidagross  @BenjaminPelletier The last time I investigated these issues was in connection with #22, and the problem still exists in the Nvidia PTX assembler, as my bug report was simply rejected because the Cuda compiler outputs code in a slightly different way, so the resulting PTX code is not emitted in `release` mode. I can still reproduce the problem on my GPUs by using the following code from #22:
```c#
[MethodImpl(MethodImplOptions.NoInlining)]
private static int Step1(int value)
{
    int result = 0;
    if (value == 1)
        result = 1337;
    return result;
}

[MethodImpl(MethodImplOptions.NoInlining)]
private static int Step2(int value)
{
    return Step1(value);
}

private static void Kernel(Index index, ArrayView<int> output)
{
    // ----------------------------------------------------------
    // a) Swap the following lines to get different results
    // b) Change the NoInlining attribute on Step2
    // c) Remove the NoInlining attribute on Step2
    // ----------------------------------------------------------
    int v1 = Step1(1);
    int v2 = Step2(2);

    output[index] = v1 + v2;
}
```
The problem is caused by the nested `if` in a method that has not been inlined by ILGPU. In this case, the PTX assembler outputs incorrect code if the optimization level is set to "O3" (the default setting for ILGPU programs). You can work around this problem by avoiding nested `if` or `loop` statements in functions that "cannot" be inlined. You can always enforce inlining of a function in ILGPU by annotating it with `MethodImpl(MethodImplOptions.AggressiveInlining)]`.

Fortunately, the new ILGPU version offers an `if` conversion to output the same code as the Cuda compiler. In the future, the rolling of the loop will be available as well 🔢

**Comment by davidagross** [comment] 2020-04-07 19:16
@m4rs-mt thank you so much for connecting these issues.  We certainly have `if`s and `for` loops all the way down, which explains why the `AggresiveInlining` in the `Context` is a successful workaround and the right approach for us.

May I ask how far in the future you might be expecting to have some of that loop inlining available?

Also, is connecting this to #22 enough to close this issue, or is there any way to better raise awareness with compiler warnings or errors when in `Release` mode and in the presence of these nested situations?  Or is this a RTFM moment (whether or not that section of the manual is yet written 😉)

**Comment by m4rs-mt** [comment] 2020-04-14 09:52
@davidagross @BenjaminPelletier I have added general support for implementing code transformations in the latest commits. My plans are to add more sophisticated transitions to convert nested `if`-statements and to unroll or unwind `loops`. This should bypass most of these problems.

I think we should add some form of analysis to warn that such functions might work "badly" in general. This can be caused by various things (like nested control flow, functions not inlined, etc.). @MoFtZ what do you think?

**Comment by MoFtZ** [comment] 2020-04-15 01:44
@m4rs-mt Are you suggesting the implementation of a [Roslyn Analyzer](https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-started-with-roslyn-analyzers?view=vs-2019) for ILGPU? I can definitely see benefits.

For me, such an analyzer is a *nice-to-have* feature rather than a *must-have* feature. In order of priority, better error messages (as per [the roadmap](http://www.ilgpu.net/Home/Roadmap)) would be more beneficial.

One concern is that a Roslyn Analyzer would be completely separate code - it would depend on much how complex logic is required. I'm not sure if this is possible, but maybe you could create a Roslyn Analyzer that used the real ILGPU engine?

**Comment by m4rs-mt** [comment] 2020-04-26 21:27
I have been thinking about a specific [Roslyn Analyzer](https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-started-with-roslyn-analyzers?view=vs-2019). However, I guess we could start with some verbose Debug-output (similar to the one emitted by the PTX assembler tool `ptxas -v`). ILGPU could simply output more detailed information about inlined/non-inlined functions, local-memory allocations, registers, call stacks and nested function calls.

**Comment by m4rs-mt** [comment] 2020-05-11 20:31
I will close this topic for now, as I have divided the main question into several smaller parts 🔢

**Closed by m4rs-mt** 2020-05-11 20:32 UTC
Labels: feature, help wanted
