### ISSUE TITLE
CopyToCPU causes "invalid device context" error without Bind()

### ISSUE THREAD

**Issue by Ruberik** [m4rs-mt/ILGPU#705] opened 2021-12-02 20:46 UTC
If I make two simultaneous calls to CopyToCPU via Parallel.Invoke(), a crash occurs unless I (also within the thread) call accelerator.Bind() first.

I think the sample code does the best job of illustrating this.

## Code
```
static void Main(string[] args) {
    using var context = Context.Create().Cuda().ToContext();
    var accs = Enumerable.Range(0, context.GetCudaDevices().Count).Select(i => context.CreateCudaAccelerator(i)).ToArray();
    var localData = new int[10_000_000];
    var localData2 = new int[10_000_000];
    var gpuData = accs.Select(acc => acc.Allocate1D(localData)).ToArray();

    gpuData[0].CopyToCPU(localData);
    gpuData[1].CopyToCPU(localData);
    Console.WriteLine("Done copying to CPU individually");

    try {
        Parallel.Invoke(
            () => gpuData[0].CopyToCPU(localData),
            () => gpuData[1].CopyToCPU(localData2));
        Console.WriteLine("Successfully copied to CPU in pairs");
    } catch (Exception e) {
        Console.WriteLine(e + "\n" + e.StackTrace);
        Console.WriteLine("Unsuccessfully copied to CPU in pairs");
    }

    Parallel.Invoke(
            () => {
                accs[0].Bind();
                gpuData[0].CopyToCPU(localData);
            },
            () => {
                accs[1].Bind();
                gpuData[1].CopyToCPU(localData2);
            });
    Console.WriteLine("Done copying to CPU in pairs with Bind");
    accs.ToList().ForEach(x => x.Dispose());
}
```

## Output
```
Done copying to CPU individually
System.AggregateException: One or more errors occurred. (invalid device context)
 ---> ILGPU.Runtime.Cuda.CudaException: invalid device context
   at ILGPU.Runtime.Cuda.CudaMemoryBuffer.CudaCopy[T](CudaStream stream, ArrayView`1& sourceView, ArrayView`1& targetView)
   at ILGPU.Runtime.Cuda.CudaMemoryBuffer.CopyTo(AcceleratorStream stream, ArrayView`1& sourceView, ArrayView`1& targetView)
   at ILGPU.Runtime.ArrayViewExtensions.CopyToCPUUnsafeAsync[T,TView](TView source, AcceleratorStream stream, T& cpuData, Int64 length)
   at ILGPU.Runtime.ArrayViewExtensions.CopyToCPU[T,TView](TView source, AcceleratorStream stream, Span`1& span)
   at ILGPU.Runtime.ArrayViewExtensions.CopyToCPU[T](ArrayView1D`2 view, AcceleratorStream stream, T[] data)
   at Gotham.FurrowUtilities.MiscClean.<>c__DisplayClass0_0.<Main>b__3() in C:\Gotham\main\FurrowUtilities\MiscClean\MiscClean.cs:line 24
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at Gotham.FurrowUtilities.MiscClean.Main(String[] args) in C:\Gotham\main\FurrowUtilities\MiscClean\MiscClean.cs:line 22
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at Gotham.FurrowUtilities.MiscClean.Main(String[] args) in C:\Gotham\main\FurrowUtilities\MiscClean\MiscClean.cs:line 22
Unsuccessfully copied to CPU in pairs
Done copying to CPU in pairs with Bind
```

**Comment by MoFtZ** [comment] 2021-12-02 21:26
@Ruberik I'm not sure there is a fix for this. Cuda is limited to a single active device context, and so you will need to manage thread-safety yourself.

Even in your workaround, were you call `Bind` before `CopyToCPU`, there is still a race condition. Thread A could call `Bind`, and then the OS could context switch to Thread B to call `Bind`. When control returns to Thread A, it will have the wrong device context.

@m4rs-mt thoughts?

**Comment by Ruberik** [comment] 2021-12-03 04:10
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#device-selection indicates this binding is per-thread.

**Comment by MoFtZ** [comment] 2021-12-03 04:27
Yes, you are correct @Ruberik.

It looks like this is might be a regression. In ILGPU v0.10, we call `Bind` before the copy operation. However, in ILGPU v1.0, I do no see the call to `Bind`.

I had assumed the `Bind` was already part of the copy operation, which is why I thought there was a race condition.

**Comment by m4rs-mt** [comment] 2021-12-03 09:38
@Ruberik and @MoFtZ Thank you for submitting and already working on this issue 👍. Yes, there is a single context per thread in the Cuda world. However, the `Bind` call has been removed because the `Copy` operation is supposed to work without an active context when using UVA addresses. The sample you posted works like a charm on my test machines with multiple accelerator. I suppose that this might be a driver thing... the "issue" was introduced in #675, since a call to `Bind` takes a long time to complete on many platforms. I propose that we reintroduce this call to bind the accelerator explicitly in all cases to avoid driver/behavior/documentation inconsistencies.

**Comment by MoFtZ** [comment] 2021-12-03 10:26
@m4rs-mt Maybe this is happening because the worker thread on the thread pool needs to be initialized/bound at least once?

**Comment by m4rs-mt** [comment] 2021-12-06 12:09
I have done further experiments and @MoFtZ seems to be right here. On "some" GPU architectures that use "certain" drivers, the copy operations seem to fail for this reason.

**Closed** 2022-01-12 21:02 UTC
Labels: bug, workaround required
