### ISSUE TITLE
Bitwise operation slow?

### ISSUE THREAD

**Issue by uler3161** [m4rs-mt/ILGPU#840] opened 2022-09-02 11:19 UTC
I just started using ILGPU yesterday, so this might just be beginner error. I tried to use the math examples to put together a solution that would do AND-ing of large byte arrays. The code is as follows:

```c#
        static byte[] TestGpu(
            byte[] b1,
            byte[] b2)
        {
            static void GpuKernel(
                Index1D index,
                ArrayView<byte> input1,
                ArrayView<byte> input2,
                ArrayView<byte> output)
            {
                output[index] = (byte)(input1[index] & input2[index]);
            }

            using var context = Context.CreateDefault();
            using var accelerator = context.GetPreferredDevice(false)
                .CreateAccelerator(context);

            using var b1Data = accelerator.Allocate1D(b1);
            using var b2Data = accelerator.Allocate1D(b2);
            using var b3Data = accelerator.Allocate1D<byte>(b1.Length);

            var kernel =
                accelerator.LoadAutoGroupedStreamKernel<Index1D, ArrayView<byte>, ArrayView<byte>, ArrayView<byte>>(
                    GpuKernel);
            kernel((int)b3Data.Length, b1Data.View, b2Data.View, b3Data.View);
            accelerator.Synchronize();

            return b3Data.GetAsArray1D();
        }
```

I've verified that the device being used is my GTX 1070. But the problem is the code is slow. I have a single for loop CPU implementation that is roughly twice as fast. For reference, I'm currently testing with randomly generated byte arrays of 200000000 items. The for loop implementation is taking around 500-600ms. The above implementation is around 1000ms. Is there something wrong with my code that is causing a massive slowdown?

**Edit 1:**

Kernel was AND-ing input1 to itself instead of input2. Fixed. Didn't affect performance.

**Comment by m4rs-mt** [comment] 2022-09-02 12:02
Hi @uler3161 and welcome to the ILGPU community! This sounds interesting. Which version of ILGPU are you using at the moment? When you are referring to the CPU implementation which is "twice as fast", which data-set size are you considering at the moment?

**Comment by uler3161** [comment] 2022-09-02 18:37
> Hi @uler3161 and welcome to the ILGPU community! This sounds interesting. Which version of ILGPU are you using at the moment? When you are referring to the CPU implementation which is "twice as fast", which data-set size are you considering at the moment?

I am using 1.2.0 which I believe is the latest stable version according to nuget.

Not entirely sure what you're asking about data-set size. Are you asking about something other than the 200000000 number I gave earlier?

> 
> A further question related to your benchmark: Are you currently measuring the whole runtime of the function `TestGPU` in your implementation?

Yes, I am testing the whole runtime. Here is the complete code I'm using:

```
    internal class Program
    {
        static void Main(
            string[] args)
        {
            var r = new Random((int)DateTime.Now.Ticks);
            const int arraySize = 200000000;

            var b1 = new byte[arraySize];
            var b2 = new byte[arraySize];

            r.NextBytes(b1);
            r.NextBytes(b2);

            var expected = TestLoop(b1, b2);

            Test(b1, b2, expected, TestLoop);
            Test(b1, b2, expected, TestGpu);
        }

        private static void Test(
            byte[] b1,
            byte[] b2,
            byte[] expected,
            Func<byte[], byte[], byte[]> tester)
        {
            var sw = new Stopwatch();
            sw.Start();

            var results = tester(b1, b2);

            sw.Stop();
            Console.WriteLine(
                $"{tester.Method.Name}: {sw.ElapsedMilliseconds}ms, Correct: {expected.SequenceEqual(results)}");
        }

        static byte[] TestGpu(
            byte[] b1,
            byte[] b2)
        {
            static void GpuKernel(
                Index1D index,
                ArrayView<byte> input1,
                ArrayView<byte> input2,
                ArrayView<byte> output)
            {
                output[index] = (byte)(input1[index] & input2[index]);
            }

            using var context = Context.CreateDefault();
            using var accelerator = context.GetPreferredDevice(false)
                .CreateAccelerator(context);

            using var b1Data = accelerator.Allocate1D(b1);
            using var b2Data = accelerator.Allocate1D(b2);
            using var b3Data = accelerator.Allocate1D<byte>(b1.Length);

            var kernel =
                accelerator.LoadAutoGroupedStreamKernel<Index1D, ArrayView<byte>, ArrayView<byte>, ArrayView<byte>>(
                    GpuKernel);
            kernel((int)b3Data.Length, b1Data.View, b2Data.View, b3Data.View);
            accelerator.Synchronize();

            return b3Data.GetAsArray1D();
        }

        static byte[] TestLoop(
            byte[] b1,
            byte[] b2)
        {
            var b3 = new byte[b1.Length];
            for (var i = 0; i < b1.Length; i++)
            {
                b3[i] = (byte)(b1[i] & b2[i]);
            }

            return b3;
        }
    }
```

**Comment by uler3161** [comment] 2022-09-02 20:59
Another sample program that I threw together to do simple addition. This program was based on the SimpleKernel sample:

```
internal class Program
    {
        static void Main(
            string[] args)
        {
            const int arraySize = 1000000;

            var expected = TestLoop(arraySize, 10);

            Test(arraySize, 10, expected, TestLoop);

            TestGpu2(arraySize, 10, expected);
        }

        static void MyKernel(
            Index1D index,
            ArrayView<int> dataView,
            int constant)
        {
            dataView[index] = index + constant;
        }

        private static void Test(
            int length,
            int constant,
            int[] expected,
            Func<int, int, int[]> tester)
        {
            var sw = new Stopwatch();
            sw.Start();

            var results = tester(length, constant);

            sw.Stop();
            Console.WriteLine(
                $"{tester.Method.Name}: {sw.ElapsedMilliseconds}ms, Correct: {expected.SequenceEqual(results)}");
        }

        static void TestGpu2(
            int length,
            int constant,
            int[] expected)
        {
            using var context = Context.CreateDefault();

            foreach (var device in context)
            {
                Func<int, int, int[]> tester = (
                    l,
                    c) =>
                {
                    using var accelerator = device.CreateAccelerator(context);
                    Console.WriteLine($"Performing operations on {accelerator}");

                    var kernel = accelerator.LoadAutoGroupedStreamKernel<Index1D, ArrayView<int>, int>(MyKernel);

                    using var buffer = accelerator.Allocate1D<int>(l);

                    kernel((int)buffer.Length, buffer.View, c);

                    return buffer.GetAsArray1D();
                };

                Test(length, constant, expected, tester);
            }
        }

        static int[] TestLoop(
            int length,
            int constant)
        {
            var b3 = new int[length];
            for (var i = 0; i < length; i++)
            {
                b3[i] = i + constant;
            }

            return b3;
        }
    }
```

Output with 1,000,000 integers:

> TestLoop: 4ms, Correct: True
> Performing operations on CPUAccelerator [Type: CPU, WarpSize: 4, MaxNumThreadsPerGroup: 16, MemorySize: 9223372036854775807]
> <TestGpu2>b__0: 369ms, Correct: True
> Performing operations on NVIDIA GeForce GTX 1070 [Type: Cuda, WarpSize: 32, MaxNumThreadsPerGroup: 1024, MemorySize: 8589606912]
> <TestGpu2>b__0: 220ms, Correct: True

With 10,000,000 integers:

> TestLoop: 36ms, Correct: True
> Performing operations on CPUAccelerator [Type: CPU, WarpSize: 4, MaxNumThreadsPerGroup: 16, MemorySize: 9223372036854775807]
> <TestGpu2>b__0: 1169ms, Correct: True
> Performing operations on NVIDIA GeForce GTX 1070 [Type: Cuda, WarpSize: 32, MaxNumThreadsPerGroup: 1024, MemorySize: 8589606912]
> <TestGpu2>b__0: 239ms, Correct: True

With 100,000,000 integers:

> TestLoop: 353ms, Correct: True
> Performing operations on CPUAccelerator [Type: CPU, WarpSize: 4, MaxNumThreadsPerGroup: 16, MemorySize: 9223372036854775807]
> <TestGpu2>b__0: 9152ms, Correct: True
> Performing operations on NVIDIA GeForce GTX 1070 [Type: Cuda, WarpSize: 32, MaxNumThreadsPerGroup: 1024, MemorySize: 8589606912]
> <TestGpu2>b__0: 457ms, Correct: True

I can't wrap my head around why a single-threaded for loop is so much faster. Even with 100,000,000 integers, it seems to still be beating the Cuda implementation, though the difference is becoming smaller.

**Comment by m4rs-mt** [comment] 2022-09-02 21:16
Oh, I see. The problem is related to fact that you are measuring context creation, accelerator initialization, kernel compilation, memory allocation *and* kernel runtime. This is an unfair comparison as the actual runtime of the kernel will be a fraction of a millisecond on the device. A proper way of measuring the kernel runtime will be:
```c#
using var context = Context.CreateDefault();
using var accel = context.CreateCudaAccelerator(0);
var kernel = accelerator.LoadAutoGroupedStreamKernel<Index1D, ArrayView<int>, int>(MyKernel);
using var buffer = accelerator.Allocate1D<int>(...);

// Do stuff in between
accel.Synchronize();
// Start measurement here
kernel(....);
accel.Synchronize()
// Stop measurement here
```

**Comment by uler3161** [comment] 2022-09-02 22:35
Thanks. 

I was able to get my original AND-ing test down to around half of what the simple loop does. For 200000000 length byte arrays, the simple loop was 567ms and ILGPU was 301ms. However, I was expecting a lot better than that. 

I'm ok with creating the context, accelerator, and kernel outside of the timing since I don't think that's going to affect how I eventually want to use ILGPU. With those extracted from the timing code, there doesn't seem to be much difference.

So, that leads to allocating the buffer. That made a big difference. And I suppose the input arrays allocating outside of the timing would help as well. But, I'm not sure that's going to work so well for what I want to use it for. The reason is that I don't know what size the arrays are until the AND-ing code gets called. And different calls will have different sized arrays. So really, buffer allocation would have to be included in the timing. I suppose I could allocate a very large buffer and then just take a subset of the resulting bytes after executing. I'm unsure if that's a good idea.

Is it safe to say that ILGPU works best if you have the following situation?

1. Know beforehand how large the arrays are. That's so you can reasonably pre-allocate.
AND
2. Have a reason to call the kernel enough times so that the total ILGPU cost (the initial allocation plus the cost of each kernel execution) is less than the total cost of another algorithm (cost of each for loop in my simple for loop implementation).

**Comment by MoFtZ** [comment] 2022-09-06 00:12
hi @uler3161,

> Is it safe to say that ILGPU works best if you have the following situation?
> 
>    1. Know beforehand how large the arrays are. That's so you can reasonably pre-allocate.

I would say this is true for any GPGPU solution, not specific to ILGPU. There is an overhead in transferring data from the CPU memory to the GPU memory.

>    AND
>
>    2. Have a reason to call the kernel enough times so that the total ILGPU cost (the initial allocation plus the cost of each kernel execution) is less than the total cost of another algorithm (cost of each for loop in my simple for loop implementation).

The compilation time is more specific to ILGPU. If you were to use Cuda with C++, the kernel would be pre-compiled along with your binary. In practice, this has generally not been an issue since you can compile the kernel at the start of your application, or on first use.

Something else you might try is to increase the workload of a single kernel. Currently, your kernel is performing a single AND operation between two values. In your example, this would mean the kernel is called 200k times. You could try getting the kernel to perform more AND operations. The idea being to reduce the overhead of calling a kernel.

**Comment by m4rs-mt** [comment] 2022-09-16 14:42
I am closing this issue for the moment. If the problem persists, we can always reopen this issue.

**Closed by m4rs-mt** 2022-09-16 14:42 UTC
Labels: help wanted, question
