### ISSUE TITLE
Failed Test for AMD GPU

### ISSUE THREAD

**Issue by 12345swordy** [m4rs-mt/ILGPU#58] opened 2019-12-29 00:56 UTC
Failed Tests:
CLAtomicCASOperations_Debug
CLAtomicCASOperations_Release
CLAtomicOperations_Debug
CLAtomicOperations_Release
CLCompareFloatOperations_Debug
CLCompareFloatOperations_Release
CLConvertFloatOperations_Debug
CLConvertFloatOperations_Release
CLUnaryIntOperations_Debug
CLUnaryIntOperations_Release
CLWrapOperations_Debug
CLWrapOperations_Release

**Comment by m4rs-mt** [comment] 2020-01-11 11:12
@12345swordy First of all: Happy New Year and thanks for running all test cases on an AMD GPU 🥇 
I will soon equip a test machine with an AMD 5500XT, so I should be able to reproduce these problems in the near future.

I had already expected that the `CLWarpOperations_Debug` test cases would fail because I could not map all shuffle instructions to corresponding `OpenCL' intrinsics supported by AMD. Do you have an idea how to express them in `OpenCL` in a portable way?

**Comment by branc116** [comment] 2020-01-14 01:34
I have cloned the master yesterday and opencl kernel worked on my amd r9 m375.

Good job and thank you. Awesome project.

**Comment by m4rs-mt** [comment] 2020-04-05 20:28
I have restructured the entire OpenCL backend to ensure that all pointers are now in the appropriate address spaces in all cases. I also successfully tested most of the tests on Intel and AMD hardware. However, you can assume that several tests on your devices might fail due to lack of hardware support on all platforms. However, the `CLUnaryIntOperations` still fail on the platforms with respect to unsigned types.

However, I will close this issue for now. If you encounter further problems, please open a special bug report.

**Closed by m4rs-mt** 2020-04-05 20:28 UTC
